"""revesion phno

Revision ID: 1a91b7553b35
Revises: 32890be343ee
Create Date: 2022-02-01 16:17:13.113170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a91b7553b35'
down_revision = '32890be343ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('PHONE_NO', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS', 'PHONE_NO')
    # ### end Alembic commands ###
