"""auto generate vote table

Revision ID: 6b47680590f4
Revises: fcda3e21ec45
Create Date: 2022-02-01 16:12:04.187991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b47680590f4'
down_revision = 'fcda3e21ec45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VOTES',
    sa.Column('USER_ID', sa.Integer(), nullable=False),
    sa.Column('POST_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['POST_ID'], ['POSTS.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['USER_ID'], ['USERS.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('USER_ID', 'POST_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VOTES')
    # ### end Alembic commands ###
